# Generated by Django 4.0 on 2022-01-13 23:20

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='tag')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='background')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='thumbnail')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('lead_text', models.TextField(max_length=120, verbose_name='lead_text')),
                ('main_text', markdownx.models.MarkdownxField(verbose_name='main_text')),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
                ('created_at', models.DateField(verbose_name='created')),
                ('color', models.CharField(choices=[('#ffffff', 'white'), ('#000000', 'black')], default='#ffffff', max_length=7, verbose_name='text_color')),
                ('tag', models.ManyToManyField(to='blog.TagModel', verbose_name='tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
